name: Run API Tests with Allure Report

on:
  workflow_dispatch:
    inputs:
      test_group:
        description: 'Select test group to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - Health
          - Booking
          - Smoke
          - Regression

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          tar -zxvf allure-2.24.0.tgz
          sudo mv allure-2.24.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Run tests with Maven
        run: |
          if [ "${{ github.event.inputs.test_group }}" == "all" ]; then
            mvn clean test
          else
            mvn clean test -Dgroups="${{ github.event.inputs.test_group }}"
          fi

      - name: Checkout gh-pages branch to get history
        run: |
          git clone --depth=1 --branch=gh-pages https://github.com/${{ github.repository }} gh-pages

      - name: Copy history from previous report
        run: |
          if [ -d gh-pages/history ]; then
            mkdir -p target/allure-results/history
            cp -r gh-pages/history/* target/allure-results/history/
          fi

      - name: Generate Allure Report with CLI
        run: |
          allure generate target/allure-results --clean -o target/allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/allure-report
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
