name: Run API Tests with Allure Report

on:
  workflow_dispatch:
    inputs:
      test_group:
        description: 'Select test group to execute'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - Health
          - Booking
          - Smoke
          - Regression

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests with Maven (generate allure results)
        run: |
          if [ "${{ github.event.inputs.test_group }}" == "all" ]; then
            mvn clean test || true
          else
            mvn clean test -Dgroups="${{ github.event.inputs.test_group }}" || true
          fi

      - name: Check if Allure Results Exist
        run: |
          echo "Listing contents of target/allure-results"
          ls -la target/allure-results || echo "No allure-results directory found!"

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Check if Allure Report Was Generated
        run: |
          echo "Listing contents of target/site/allure-maven-plugin"
          ls -la target/site/allure-maven-plugin

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/allure-maven-plugin
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
