name: Run API Tests with Allure Report

on:
  workflow_dispatch:
    inputs:
      test_group:
        description: 'Select test you want to execute'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - Health
          - Booking
          - Smoke
          - Regression

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests and generate Allure report
        run: |
          if [ "${{ github.event.inputs.test_group }}" == "all" ]; then
            mvn clean test
          else
            mvn clean test -Dgroups="${{ github.event.inputs.test_group }}"
          fi
          mvn allure:report

      - name: List Allure Report Files
        run: ls -la target/site/allure-maven-plugin

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/allure-maven-plugin
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
