name: Run API Tests and Publish Allure Report with History

on:
  workflow_dispatch:
    inputs:
      test_group:
        description: 'Select test group to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - Health
          - Booking
          - Smoke
          - Regression

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Allure commandline
        run: |
          sudo apt-get update
          sudo apt-get install -y allure

      - name: Fetch gh-pages branch for history
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages
        continue-on-error: true

      - name: Copy history from previous report (if exists)
        run: |
          mkdir -p target/allure-results/history
          cp -r gh-pages/history target/allure-results/ || true

      - name: Run tests (allow failures)
        run: |
          if [ "${{ github.event.inputs.test_group }}" == "all" ]; then
            mvn clean test || true
          else
            mvn clean test -Dgroups="${{ github.event.inputs.test_group }}" || true
          fi

      - name: Generate Allure report
        run: mvn allure:report

      - name: Copy new history into report
        run: |
          mkdir -p target/site/allure-maven-plugin/history
          cp -r target/allure-results/history target/site/allure-maven-plugin/ || true

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/site/allure-maven-plugin
